export const Images = {
    auto: require('./auto.png'),
    bike: require('./bike.png'),
    bike1: require('./bike1.png'),
    bike2: require('./bike2.png'),
    byke: require('./byke.png'),
    foot: require('./foot.png'),
    hide: require('./hide.png'),
    motoroler: require('./motoroler.png'),
    motoroler1: require('./motoroler1.png'),
    motoroler2: require('./motoroler2.png'),
    ic_check_box_outline_blank: require('./ic_check_box_outline_blank.png'),
    ic_check_box: require('./ic_check_box.png'),
    scooter: require('./scooter.png'),
    scooter1: require('./scooter1.png'),
    scooter2: require('./scooter2.png'),
    view: require('./view.png'),
    back:require('./back.png'),
    select:require('./select.png'),
    menu:require('./menu.png'),
    refresh:require('./refresh.png'),
    people:require('./people.png'),
    people2:require('./people2.png'),
    qrcode:require('./qrcode.png'),
    qrcodemenu:require('./qrcodemenu.png'),
    charge100:require('./charge100.png'),
    charge50:require('./charge50.png'),
    charge20:require('./charge20.png'),
    close:require('./close.png'),
    map:require('./map.png'),
    logo:require('./logo.png'),
  };